### ISSUE TITLE
Question about the difference between the semi-synthetic adult dataset generation

### ISSUE THREAD

**Issue by hanxiao0607** [psanch21/VACA#1]
Hi there, thanks for sharing your code for VACA. As in the paper, income is related to age, and the income will be increased by 3,000 if 21<=age<30, or 8,000 if age>=30. While in the code "output += 3000 * (age >= 21) & (age < 30) + 8000 * (age >= 30)", it does bitwise & operation which is not the same as mentioned in your paper. For instance, if the age =32, then the output for your code will be 2,816 instead of 8,000. Please let me know if i get it wrong. Thanks!

**Comment by psanch21** [comment]
Hi Xiao Han,

You are totally right!  We will update the description of the Adult dataset in Appendix E of the paper to make it clear we are using the bitwise operator in several of the structural equations, such that the description matches the code.

Thank you for taking note of that!  Let me know if you need further clarification.

**Comment by hanxiao0607** [comment]
Thanks for the clarification!
